"""Constants for the Priority Switch integration."""

DOMAIN = "priorityswitch"
DOMAIN_FRIENDLY = "Priority Switch"
CONF_INPUTS = "inputs"
ATTR_CONTROL_STATE = "control_state"
ATTR_CONTROL_ENTITY = "control_entity"
ATTR_CONTROL_ENTITY_VALUE = "control_entity_value"
ATTR_CONTROL_TEMPLATE = "control_template"
ATTR_CONTROL_TEMPLATE_VALUE = "control_template_value"
ATTR_CONTROL_TYPE = "control_type"
ATTR_VALUE = "value"
ATTR_VALUE_TYPE = "value_type"
ATTR_VALUE_TEMPLATE = "value_template"
ATTR_VALUE_ENTITY = "value_entity"
PLATFORMS = ["sensor"]
