name: HACS Action

on:
  push:
  #pull_request:
  #schedule:
  #  - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "https://github.com/hacs/action@main"
        with:
          category: "appdaemon"